repos:
  - repo: local
    hooks:
      - id: pre-commit (src & examples)
        name: pre-commit
        description: "Run pre-commit task via hatch"
        entry: hatch run pre_commit
        language: system
        additional_dependencies: []
        minimum_pre_commit_version: "0"
