import typing

from _algopy_testing.constants import UINT64_BYTES_LENGTH
from _algopy_testing.context_helpers import lazy_context
from _algopy_testing.primitives.bytes import Bytes
from _algopy_testing.primitives.uint64 import UInt64
from _algopy_testing.protocols import BytesBacked
from _algopy_testing.utils import int_to_bytes


def log(
    *args: UInt64 | Bytes | BytesBacked | str | bytes | int,
    sep: Bytes | bytes | str = b"",
) -> None:
    """Concatenates and logs supplied args as a single bytes value.

    UInt64 args are converted to bytes and each argument is separated by `sep`.
    Literal `str` values will be encoded as UTF8.
    """
    logs: list[bytes] = []

    for arg in args:
        if isinstance(arg, UInt64):
            logs.append(int_to_bytes(arg.value, pad_to=UINT64_BYTES_LENGTH))
        elif isinstance(arg, Bytes):
            logs.append(arg.value)
        elif isinstance(arg, str):
            logs.append(arg.encode("utf8"))
        elif isinstance(arg, bytes):
            logs.append(arg)
        elif isinstance(arg, int):
            logs.append(int_to_bytes(arg, pad_to=UINT64_BYTES_LENGTH))
        else:
            logs.append(arg.bytes.value)

    if isinstance(sep, Bytes):
        separator = sep.value
    elif isinstance(sep, str):
        separator = sep.encode("utf8")
    else:
        separator = sep

    active_txn = lazy_context.active_group.active_txn
    active_txn.append_log(separator.join(logs))


def logged_assert(
    condition: bool,  # noqa: FBT001
    /,
    error_code: typing.LiteralString,
    error_message: typing.LiteralString | None = None,
    prefix: typing.Literal["AER", "ERR"] = "ERR",
) -> None:
    """Asserts that a condition is true, logging a formatted error message before
    failing if the condition is false.

    The logged output follows the format ``{prefix}:{error_code}`` or
    ``{prefix}:{error_code}:{error_message}`` and is compatible with ARC-56 and ARC-32 clients.

    Note this increases the generated bytecode, so keeping ``error_code`` and ``error_message``
    short is recommended.

    :arg condition: The condition to assert; if false, logs an error and fails.
    :arg error_code: An alphanumeric error code. Must not contain ``:``.
    :arg error_message: Optional message appended after the code. Must not contain ``:``.
    :arg prefix: Error prefix, either ``"AER"`` or ``"ERR"``.
    """
    if condition:
        return
    msg = _resolve_error_message(error_code, error_message, prefix)
    log(msg)
    raise RuntimeError(msg)


def logged_err(
    error_code: typing.LiteralString,
    error_message: typing.LiteralString | None = None,
    prefix: typing.Literal["AER", "ERR"] = "ERR",
) -> None:
    """Logs a formatted error message and immediately fails the transaction.

    Note this is equivalent to ``logged_assert(False, error_code, error_message, prefix)``.
    This function increases the generated bytecode, so keeping ``error_code`` and ``error_message``
    short is recommended.

    The logged output follows the ARC-65 format ``{prefix}:{error_code}`` or
    ``{prefix}:{error_code}:{error_message}`` and is compatible with ARC-56 and ARC-32 clients.

    :arg error_code: An alphanumeric error code. Must not contain ``:``.
    :arg error_message: Optional message appended after the code. Must not contain ``:``.
    :arg prefix: Error prefix, either ``"AER"`` or ``"ERR"``.
    """
    msg = _resolve_error_message(error_code, error_message, prefix)
    log(msg)
    raise RuntimeError(msg)


_VALID_PREFIXES = frozenset({"ERR", "AER"})


def _resolve_error_message(
    code: str,
    message: str | None = None,
    prefix: str = "ERR",
) -> str:
    if ":" in code:
        raise ValueError("error code must not contain domain separator ':'")
    if message and ":" in message:
        raise ValueError("error message must not contain domain separator ':'")
    if prefix not in _VALID_PREFIXES:
        raise ValueError("error prefix must be one of AER, ERR")

    if message:
        return f"{prefix}:{code}:{message}"
    else:
        return f"{prefix}:{code}"
