name: Check Python Code (algopy_testing)

on:
  workflow_call:
  pull_request:
  schedule:
    - cron: "0 8 * * 1" # Each monday 8 AM UTC

jobs:
  check-python:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install hatch
        run: pip install hatch

      - name: Start LocalNet
        run: pipx install algokit && algokit localnet start

      - name: Check pre-commits
        run: hatch run check

      - name: Check pre-commits (examples)
        run: hatch run examples:check

      - name: Validate examples folder
        run: hatch run validate_examples

      - name: Check wheels can be built
        run: hatch build

      - name: Run tests (codebase)
        run: hatch run tests

      - name: Run tests (examples)
        run: hatch run examples:tests

      - name: Check doctests
        run: hatch run docs:test
