name: Publish docs to GitHub Pages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build and upload docs artifact
        uses: ./.github/actions/build-documentation
        with:
          node-version: 22.x
          upload-pages-artifact: 'true'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
