name: Publish DevPortal Docs

on:
  workflow_dispatch:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docs
        uses: ./.github/actions/build-documentation
        with:
          node-version: 22.x
          upload-pages-artifact: 'false'

      - name: Publish DevPortal Docs
        uses: algorandfoundation/devportal/.github/actions/publish-devportal-docs@ci/update-publish-devportal-docs-workflow
        with:
          docs-dir: docs
